"""Domain errors exposed by the runtime control plane."""


class GpuRuntimeError(RuntimeError):
    """Base class for expected runtime errors."""


class InvalidIdentifierError(ValueError, GpuRuntimeError):
    """A session, event, or snapshot identifier is unsafe."""


class DuplicateSessionError(GpuRuntimeError):
    """A session already exists."""


class SessionNotFoundError(GpuRuntimeError):
    """A requested session does not exist."""


class VersionConflictError(GpuRuntimeError):
    """A learn request was generated by a stale policy version."""


class EventConflictError(GpuRuntimeError):
    """An event id was reused with a different payload."""


class SnapshotIntegrityError(GpuRuntimeError):
    """A snapshot is incomplete, corrupt, or belongs to another session."""


class SnapshotNotFoundError(GpuRuntimeError):
    """A requested snapshot does not exist."""
